import Head from 'next/head';
import { Inter } from '@next/font/google';
import styles from '../styles/Home.module.css';
import { signIn, signOut, useSession } from 'next-auth/react';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
	const { data: session } = useSession();

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className={styles.main}>
				<div className={styles.description}>
					{session && session.user ? (
						<button onClick={() => signOut()}>Sign Out</button>
					) : (
						<button onClick={() => signIn()}>Sign In</button>
					)}
				</div>

				{session && session.user ? (
					<div>Login</div>
				) : (
					<div>not login</div>
				)}
			</main>
		</>
	);
}
